### ISSUE TITLE
Keep getting this error !

### ISSUE THREAD

**Issue by krizmatic** [Virus18sp/truck_logistics#2]
![image](https://user-images.githubusercontent.com/58721529/126890480-40f80cc1-f9cc-4f35-ac86-6e37fcd6dc1f.png)

This appears when upgrading the distance skill.

**Comment by krizmatic** [comment]
![image](https://user-images.githubusercontent.com/58721529/127082454-8f1ae34f-456e-4e5f-96c6-5750b9bb8701.png)

In the skill upgrading menu in UI, players can only increase their distance skill and this error happens when they try to upgrade their fragile , valuable,etc.

**Comment by Virus18sp** [comment]
Fixed.
