### ISSUE TITLE
Not compatible with onxmysql

### ISSUE THREAD

**Issue by jawsoccer** [Virus18sp/truck_logistics#4]
Script does not work with the required update to onxmysql that the qbcore framework has moved to.

**Comment by balcer64** [comment]
it also doesn't work very well with "ghmattimysql", everything is registered in the database, the truck, the balance is all there, but cars and trailers will not appear, writes your truck will appear now, but nothing happens

**Comment by Virus18sp** [comment]
The script works perfectly but it is not yet adapted for oxmysql, I will do it in my spare time. Otherwise the script works perfectly, I use it on my server and many more people use it without problem, the trucks spawn without problem and you can close and open them because the system gives you the key and you can see it on the client, verify that everything is compatible with your version, triggers and others that you have nothing changed. I can't make it compatible for everyone because not everyone uses the same versions of qbcore, some continue to use an older version, some a more modern one and others the current one. This script is based on the version of qbcore from about 3 months ago and apart from oxmysql everything works perfectly with any stock qbcore.

**Comment by Slay3rIQ** [comment]
Can’t wait for the oxmysl version. Scripts looks amazing

**Comment by balcer64** [comment]
> Скрипт работает отлично, но еще не адаптирован для oxmysql, буду заниматься в свободное время. В остальном скрипт работает отлично, я использую его на своем сервере, и многие люди используют его без проблем, грузовики появляются без проблем, и вы можете закрывать и открывать их, потому что система дает вам ключ, и вы можете увидеть его на клиенте, проверить что все совместимо с вашей версией, триггерами и прочим, что вы ничего не меняли. Я не могу сделать его совместимым для всех, потому что не все используют одни и те же версии qbcore, некоторые продолжают использовать более старую версию, некоторые более современную, а другие текущую. Этот скрипт основан на версии qbcore, выпущенной около 3 месяцев назад, и, кроме oxmysql, все отлично работает с любым стандартным qbcore.

tell me what I'm doing wrong, the markers are working, everything is also written to the database, but after clicking the "get auto" or "task" button, nothing happens, maybe I'm missing something? do I need to register cars somewhere in the files?
![Screenshot_5](https://user-images.githubusercontent.com/22128071/136826043-42a2561c-784d-466f-b202-eb364bed98a8.jpg)

**Comment by d-w00d** [comment]
Has anyone successfully converted to new SQL Wrapper?

**Comment by Zulu1uk** [comment]
> Has anyone successfully converted to new SQL Wrapper?

no

**Comment by NegraLyda** [comment]
Didn't it convert to oxmysql?

**Comment by Goykz** [comment]
points are not updating in database at all XP seems to work but the skill points do not i add skill points in the database manually and it works but the script doesn't up date it automatically.

**Comment by Virus18sp** [comment]
Some pull request has been merged for oxmysql, try it, i just merged dint tested, sorry.

**Comment by Goykz** [comment]
exports.oxmysql:fetch is no longer used needs to be exports.oxmysql:query

**Comment by Goykz** [comment]
![image](https://user-images.githubusercontent.com/94883534/151824484-eb1373b6-bc4e-433f-8ffa-63bb26d95f04.png)
doesn't work unfortunately

**Comment by Virus18sp** [comment]
> ![image](https://user-images.githubusercontent.com/94883534/151824484-eb1373b6-bc4e-433f-8ffa-63bb26d95f04.png)
> doesn't work unfortunately

Go to your sql and change all columns with bit(1) to tinyint

**Comment by JReagan618** [comment]
Trucks are spawning locked and not lockpickable....I've done everything that I read here, not sure what to do from here. No errors  :(

**Comment by Forfeit05** [comment]
If you restart the script and start the job it bugs out and you have to lockpick it. After that it's fine.

**Comment by Virus18sp** [comment]
As i say tons of times this script was converted for and early stage of qbcore since this qbcore have received thousands of updates. If have problems with keys go to client and compare vehiclekeys trigger with latest vehiclekeys and perform the correct updates.

**Comment by Forfeit05** [comment]
Nah your convert is fine. Just letting them know what the script does in start. People's just gotta be patient and work it out.

**Comment by Kxcp3r** [comment]
Can this be updated?
