### ISSUE TITLE
No Such Export in Oxmysql

### ISSUE THREAD

**Issue by Adyan123** [Virus18sp/truck_logistics#8]
![image](https://user-images.githubusercontent.com/69138291/153049364-fe3485cb-a3a0-47da-9759-73404163a8cc.png)

**Comment by Virus18sp** [comment]
What version of oxmysql are you using? if is the latest i think the removed export function.

**Comment by Adyan123** [comment]
how to solve this i m using latest qbcore

**Comment by w6o** [comment]
Yes this still a problem tryna do the same thing i have the same problem as him using the newest version of qb-core + newest version of oxmysql

**Comment by w6o** [comment]
Even gone back to oxmysql 1.9 and it still have the same issue

**Comment by w6o** [comment]
Just to let you know if you would like to use this script you'll have to downgrade oxmysql from 1.9.3 all the way down to 1.8.5. maybe 1.8.6 works but you have to figure that out on your own.

**Comment by w6o** [comment]
It would be nice if u could update it from the new updates that are coming out for the script if you still have availability and if they have updated the script due its a very nice script and it looks good and i believe it will work good but if you are not able to use oxmysql 1.9+ that is a bit odd due you'll have to downgrade the mods eitherway

**Comment by Adyan123** [comment]
Yes Virus please update it to latest oxmysql

**Comment by GabbarFramework** [comment]
![image](https://user-images.githubusercontent.com/98814269/156128753-8ac0b954-7c86-4202-a744-0a1c1b21ef0c.png)
using 1.9.3
